# 데이터 준비

In [1]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

In [ ]:
import os
from glob import glob
import math
import re

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
!ls '/gdrive/MyDrive/0. 인공지능 학습/아이펠 대전 3기/5. 해커톤/1차 해커톤/data'

디즈니	아마존	파라마운트  넷플릭스

In [ ]:
data_dir = '/gdrive/MyDrive/0. 인공지능 학습/아이펠 대전 3기/5. 해커톤/1차 해커톤/processed_data3'
save_data_dir = '/gdrive/MyDrive/0. 인공지능 학습/아이펠 대전 3기/5. 해커톤/1차 해커톤/processed_data4'
platform_names = ["amazon", "netflix", "disney", "paramount"]

credits_path = os.path.join(data_dir, "merged_credits.csv")
amazon_titles_path = os.path.join(data_dir, "merged_titles.csv")

In [ ]:
credits = pd.read_csv(credits_path)
titles = pd.read_csv(amazon_titles_path)

# 국가명 컬럼 추가

In [ ]:
def make_unique_country_list(df, platform_names):
    country_lists = []
    all_platforms_country_lists = []
    for i, platform_name in enumerate(platform_names):
        # 데이터 프레임 중 특정 플랫폼을 추출하여 국가 데이터의 유니크 값 목록 생성
        country_df = titles.loc[titles["platform"] == platform_name]
        unique_country_list = country_df["production_countries"].unique()

        country_list = []
        # 문자열 치환 후 국가 리스트 생성
        for countries in unique_country_list:
            temp_countries = re.sub('\[', "", countries)
            temp_countries = re.sub('\]', "", temp_countries)
            temp_countries = re.sub("\'", "", temp_countries)
            temp_countries = re.sub(' ', "", temp_countries)
            temp_countries = temp_countries.split(",")

            country_list.extend(temp_countries)

        # 플랫폼 별 국가명 리스트 생성
        country_lists.append(country_list)
        # 모든 플랫폼에 대한 국가명 리스트 생성
        all_platforms_country_lists.extend(country_list)

    return country_lists, all_platforms_country_lists

In [ ]:
country_lists, all_platforms_country_lists = make_unique_country_list(titles, platform_names)

- 개별 플랫폼 별 국가 종류 리스트 생성
- 모든 플랫폼을 통합한 국가 종류 리스트 생성

In [ ]:
country_column_names = set(all_platforms_country_lists)
country_column_names

{'',
 'AE',
 'AF',
 'AL',
 'AM',
 'AN',
 'AO',
 'AQ',
 'AR',
 'AT',
 'AU',
 'BA',
 'BD',
 'BE',
 'BF',
 'BG',
 'BM',
 'BO',
 'BR',
 'BS',
 'BY',
 'CA',
 'CD',
 'CH',
 'CI',
 'CL',
 'CM',
 'CN',
 'CO',
 'CR',
 'CU',
 'CY',
 'CZ',
 'DE',
 'DK',
 'DO',
 'DZ',
 'EE',
 'EG',
 'ES',
 'ET',
 'FI',
 'FJ',
 'FO',
 'FR',
 'GB',
 'GE',
 'GH',
 'GL',
 'GQ',
 'GR',
 'GT',
 'HK',
 'HN',
 'HR',
 'HU',
 'ID',
 'IE',
 'IL',
 'IN',
 'IO',
 'IQ',
 'IR',
 'IS',
 'IT',
 'JM',
 'JO',
 'JP',
 'KE',
 'KG',
 'KH',
 'KI',
 'KR',
 'KW',
 'KZ',
 'LB',
 'LI',
 'LT',
 'LU',
 'LV',
 'LY',
 'Lebanon',
 'MA',
 'MC',
 'MN',
 'MT',
 'MU',
 'MW',
 'MX',
 'MY',
 'MZ',
 'NG',
 'NL',
 'NO',
 'NP',
 'NZ',
 'PA',
 'PE',
 'PF',
 'PH',
 'PK',
 'PL',
 'PR',
 'PS',
 'PT',
 'PY',
 'QA',
 'RO',
 'RS',
 'RU',
 'SA',
 'SE',
 'SG',
 'SI',
 'SK',
 'SN',
 'SO',
 'SU',
 'SUHH',
 'SV',
 'SY',
 'SZ',
 'TC',
 'TH',
 'TN',
 'TR',
 'TT',
 'TW',
 'TZ',
 'UA',
 'UG',
 'US',
 'UY',
 'UnitedStatesofAmerica',
 'VA',
 'VE',
 'VN',
 'XC',
 'XK',
 'XX',
 'YU',
 'ZA',
 'ZM',
 'ZW'}

- 데이터에 과거의 국가를 지칭하는 국가 코드들이 포함되어 있음을 확인.
- Lebanon : 레바논
- SUHH : 구소련
- UnitedStatesofAmerica : 미국

In [ ]:
# 공백 제거
country_column_names.discard("")
# 예외사항 제거
country_column_names.discard("Lebanon")
country_column_names.discard("SUHH")
country_column_names.discard("UnitedStatesofAmerica")
# 아무 국가도 없는 경우에 대한 컬럼 추가
country_column_names.add("none_country")
country_column_names

{'AE',
 'AF',
 'AL',
 'AM',
 'AN',
 'AO',
 'AQ',
 'AR',
 'AT',
 'AU',
 'BA',
 'BD',
 'BE',
 'BF',
 'BG',
 'BM',
 'BO',
 'BR',
 'BS',
 'BY',
 'CA',
 'CD',
 'CH',
 'CI',
 'CL',
 'CM',
 'CN',
 'CO',
 'CR',
 'CU',
 'CY',
 'CZ',
 'DE',
 'DK',
 'DO',
 'DZ',
 'EE',
 'EG',
 'ES',
 'ET',
 'FI',
 'FJ',
 'FO',
 'FR',
 'GB',
 'GE',
 'GH',
 'GL',
 'GQ',
 'GR',
 'GT',
 'HK',
 'HN',
 'HR',
 'HU',
 'ID',
 'IE',
 'IL',
 'IN',
 'IO',
 'IQ',
 'IR',
 'IS',
 'IT',
 'JM',
 'JO',
 'JP',
 'KE',
 'KG',
 'KH',
 'KI',
 'KR',
 'KW',
 'KZ',
 'LB',
 'LI',
 'LT',
 'LU',
 'LV',
 'LY',
 'MA',
 'MC',
 'MN',
 'MT',
 'MU',
 'MW',
 'MX',
 'MY',
 'MZ',
 'NG',
 'NL',
 'NO',
 'NP',
 'NZ',
 'PA',
 'PE',
 'PF',
 'PH',
 'PK',
 'PL',
 'PR',
 'PS',
 'PT',
 'PY',
 'QA',
 'RO',
 'RS',
 'RU',
 'SA',
 'SE',
 'SG',
 'SI',
 'SK',
 'SN',
 'SO',
 'SU',
 'SV',
 'SY',
 'SZ',
 'TC',
 'TH',
 'TN',
 'TR',
 'TT',
 'TW',
 'TZ',
 'UA',
 'UG',
 'US',
 'UY',
 'VA',
 'VE',
 'VN',
 'XC',
 'XK',
 'XX',
 'YU',
 'ZA',
 'ZM',
 'ZW',
 'none_country'}

- 과거의 국가 코드들은 삭제하고 데이터 분리 시 예외처리 수행하겠음.

In [ ]:
country_lists[0]

In [ ]:
country_lists[1]

In [ ]:
country_lists[2]

In [ ]:
country_lists[3]

# 국가명 컬럼 데이터 추가

In [ ]:
# 국가명 컬럼 추가 후 0으로 값 설정
for country_column_name in country_column_names:
    if country_column_name == "none_country":
        continue
    titles[country_column_name] = 0
titles["none_country"] = 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

In [ ]:
# 데이터 프레임에서 제작 국가의 컬럼 인덱스 찾기
titles_columns = list(titles.columns)
production_countries_index = titles_columns.index("production_countries")

for i, countries in enumerate(titles["production_countries"]):
    temp_countries = re.sub('\[', "", countries)
    temp_countries = re.sub('\]', "", temp_countries)
    temp_countries = re.sub("\'", "", temp_countries)
    temp_countries = re.sub(' ', "", temp_countries)
    temp_country_list = temp_countries.split(",")

    for temp_country in temp_country_list:
        # 예외처리1(공백 즉 ''일 경우 none_country에 1 추가)
        if temp_country == "":
            production_countries_index = titles_columns.index("none_country")
            titles.iloc[i, production_countries_index] = 1
            continue

        # 예외처리2(국가명 코드가 Lebanon일 경우 LB에 1 추가)
        if temp_country == "Lebanon":
            production_countries_index = titles_columns.index("LB")
            titles.iloc[i, production_countries_index] = 1
            continue

        # 예외처리3(국가명 코드가 SUHH일 경우 SU에 1 추가)
        if temp_country == "SUHH":
            production_countries_index = titles_columns.index("SU")
            titles.iloc[i, production_countries_index] = 1
            continue

        # 예외처리4(국가명 코드가 UnitedStatesofAmerica 경우 US에 1 추가)
        if temp_country == "UnitedStatesofAmerica":
            production_countries_index = titles_columns.index("US")
            titles.iloc[i, production_countries_index] = 1
            continue

        # 국가명 컬럼에 데이터 추가
        production_countries_index = titles_columns.index(temp_country)
        titles.iloc[i, production_countries_index] = 1

# 장르명 컬럼 추가

In [ ]:
def make_unique_genre_list(df, platform_names):
    genre_lists = []
    all_platforms_genre_lists = []
    for i, platform_name in enumerate(platform_names):
        # 데이터 프레임 중 특정 플랫폼을 추출하여 국가 데이터의 유니크 값 목록 생성
        genre_df = titles.loc[titles["platform"] == platform_name]
        unique_genre_list = genre_df["genres"].unique()

        genre_list = []
        # 문자열 치환 후 국가 리스트 생성
        for genres in unique_genre_list:
            temp_genres = re.sub('\[', "", genres)
            temp_genres = re.sub('\]', "", temp_genres)
            temp_genres = re.sub("\'", "", temp_genres)
            temp_genres = re.sub(' ', "", temp_genres)
            temp_genres = temp_genres.split(",")

            genre_list.extend(temp_genres)

        # 개별 플랫폼에 대한 장르명 리스트 생성
        genre_lists.append(genre_list)
        # 모든 플랫폼에 대한 장르명 리스트 생성
        all_platforms_genre_lists.extend(genre_list)

    return genre_lists, all_platforms_genre_lists

In [ ]:
genre_lists, all_platforms_genre_lists = make_unique_genre_list(titles, platform_names)

In [ ]:
genre_column_names = set(all_platforms_genre_lists)
genre_column_names

{'',
 'action',
 'animation',
 'comedy',
 'crime',
 'documentation',
 'drama',
 'european',
 'family',
 'fantasy',
 'history',
 'horror',
 'music',
 'reality',
 'romance',
 'scifi',
 'sport',
 'thriller',
 'war',
 'western'}

In [ ]:
# 공백 제거
genre_column_names.discard("")
# 아무 장르도 없는 경우에 대한 컬럼 추가
genre_column_names.add("none_genre")
genre_column_names

{'action',
 'animation',
 'comedy',
 'crime',
 'documentation',
 'drama',
 'european',
 'family',
 'fantasy',
 'history',
 'horror',
 'music',
 'none_genre',
 'reality',
 'romance',
 'scifi',
 'sport',
 'thriller',
 'war',
 'western'}

- 장르가 없는 경우 데이터 분리 시 예외처리 수행하겠음.

In [ ]:
genre_lists[0]

In [ ]:
genre_lists[1]

In [ ]:
genre_lists[2]

In [ ]:
genre_lists[3]

# 장르명 컬럼 데이터 추가

In [ ]:
# 장르명 컬럼 추가 후 0으로 값 설정
for genre_column_name in genre_column_names:
    if genre_column_name == "none_genre":
        continue
    titles[genre_column_name] = 0
titles["none_genre"] = 0

In [ ]:
# 데이터 프레임에서 장르의 컬럼 인덱스 찾기
titles_columns = list(titles.columns)
genres_index = titles_columns.index("genres")

for i, genres in enumerate(titles["genres"]):
    temp_genres = re.sub('\[', "", genres)
    temp_genres = re.sub('\]', "", temp_genres)
    temp_genres = re.sub("\'", "", temp_genres)
    temp_genres = re.sub(' ', "", temp_genres)
    temp_genres_list = temp_genres.split(",")

    for temp_genre in temp_genres_list:
        # 예외처리1(공백 즉 ''일 경우 none_genre에 1 추가)
        if temp_genre == "":
            genres_index = titles_columns.index("none_genre")
            titles.iloc[i, genres_index] = 1
            continue

        # 장르명 컬럼에 데이터 추가
        genres_index = titles_columns.index(temp_genre)
        titles.iloc[i, genres_index] = 1

# 제한 연령 컬럼 및 데이터 추가

In [ ]:
titles["age_certification"].unique()

array(['TV-PG', nan, 'PG', 'G', 'PG-13', 'R', 'TV-G', 'TV-Y', 'TV-14',
       'NC-17', 'TV-Y7', 'TV-MA'], dtype=object)

- 미국 기준의 연령 제한만 존재함.
- all : G, TV-G, TV-Y
- 7+ : PG, TV-Y7, TV-PG
- 13+ : PG-13
- 16+ : TV-14
- 18+ : NC-17, R, TV-MA

In [ ]:
titles["num_age_certification"] = "none"

In [ ]:
# 데이터 프레임에서 age_certification의 컬럼 인덱스 찾기
titles_columns = list(titles.columns)
age_column_index = titles_columns.index("num_age_certification")

for i, age in enumerate(titles["age_certification"]):
    # all
    if age == "G" or age == "TV-G" or age == "TV-Y":
        titles.iloc[i, age_column_index] = "all"
    # 7+
    elif age == "PG" or age == "TV-Y7" or age == "TV-PG":
        titles.iloc[i, age_column_index] = "7+"
    # 13+
    elif age == "PG-13":
        titles.iloc[i, age_column_index] = "13+"
    # 16+
    elif age == "TV-14":
        titles.iloc[i, age_column_index] = "16+"
    # 18+
    elif age == "NC-17" or age == "R" or age == "TV-MA":
        titles.iloc[i, age_column_index] = "18+"

# 데이터 저장

In [ ]:
# titles.csv 저장
save_data_path = os.path.join(save_data_dir, "merged_titles.csv")
print("저장 경로 :", save_data_path)
titles.to_csv(save_data_path, index=False)

# credits.csv 저장
save_data_path = os.path.join(save_data_dir, "merged_credits.csv")
print("저장 경로 :", save_data_path)
credits.to_csv(save_data_path, index=False)

저장 경로 : /gdrive/MyDrive/0. 인공지능 학습/아이펠 대전 3기/5. 해커톤/1차 해커톤/processed_data4/merged_titles.csv
저장 경로 : /gdrive/MyDrive/0. 인공지능 학습/아이펠 대전 3기/5. 해커톤/1차 해커톤/processed_data4/merged_credits.csv

In [ ]:
titles

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,...,animation,horror,documentation,european,western,scifi,drama,comedy,none_genre,num_age_certification
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,...,1,1,0,0,0,0,0,1,0,7+
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,...,0,0,0,1,1,0,1,1,0,none
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,NaN,171,"['romance', 'war', 'drama']",['US'],NaN,...,0,0,0,0,0,0,1,0,0,none
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,NaN,92,"['comedy', 'drama', 'romance']",['US'],NaN,...,0,0,0,0,0,0,1,1,0,none
4,tm56584,In a Lonely Place,MOVIE,An aspiring actress begins to suspect that her...,1950,NaN,94,"['thriller', 'drama', 'romance']",['US'],NaN,...,0,0,0,0,0,0,1,0,0,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17372,tm1099382,The 26th Street Garage: The FBI's Untold Story...,MOVIE,"The story of ingenuity, teamwork and determina...",2021,NaN,58,['documentation'],[],NaN,...,0,0,1,0,0,0,0,0,0,none
17373,tm975981,Cher & the Loneliest Elephant,MOVIE,"""The World's Loneliest Elephant"" Kaavan will f...",2021,NaN,46,['documentation'],"['KH', 'PK', 'GB', 'US']",NaN,...,0,0,1,0,0,0,0,0,0,none
17374,tm1106415,Destination Porto: The Unimaginable Journey,MOVIE,Follow soccer journalist Guillem Belagué as he...,2021,PG,85,['documentation'],[],NaN,...,0,0,1,0,0,0,0,0,0,7+
17375,ts305329,House Calls with Dr. Phil,SHOW,The talk show legend travels across the countr...,2021,TV-14,43,['reality'],['US'],1.0,...,0,0,0,0,0,0,0,0,0,16+
17376,tm1100359,Race Against Time: The CIA and 9/11,MOVIE,Follows former top officials and elite operati...,2021,NaN,89,['documentation'],[],NaN,...,0,0,1,0,0,0,0,0,0,none

<img src='https://drive.google.com/uc?export=download&id=1CQgJbAwPE2QpAAinOKa7yHy97qIri-MG' width="" height ="" /><br>